export const USER_INFO = 'userInfo'
export const SET_TOKEN = 'setToken'
export const ADD_CART = 'addCart'
export const UPDATE_CART_COUNT = 'updateCartCount'
export const SAVE_POSITION = 'savePosition'
export const SAVE_ORDER_ID = 'saveOrderID'
//export const GOODS = 'manageGoodData'
