interface addProductRulesInterface{
    description:[
        {
            required:boolean,
            message:string,
            trigger:string
        }
    ],
    imageLink:[
        {
            required:boolean,
            message:string,
            trigger:string
        }
    ],
    productCount:[
        {
            type:string,
            message:string,
            trigger:string
        },
        {
            required:boolean,
            message:string,
            trigger:string
        }
    ],
    price:[
        {
            type:string,
            message:string,
            trigger:string
        },
        {
            required:boolean,
            message:string,
            trigger:string
        }
    ],
    brand:[
        {
            required:boolean,
            message:string,
            trigger:string
        }
    ],
    sizeCheckList:[
        {
            type:string,
            required:boolean,
            message:string,
            trigger:string
        }
    ],
    seasonCheckList:[
        {
            type:string,
            required:boolean,
            message:string,
            trigger:string
        }
    ],
    collarTypeCheckList:[
        {
            type:string,
            required:boolean,
            message:string,
            trigger:string
        }
    ]
}

export const addProductRules:addProductRulesInterface = {
    description:[
        {
            required:true,
            message:'商品描述不能为空！',
            trigger:'blur'
        }
    ],
    imageLink:[
        {
            required:true,
            message:'图片链接不能为空！',
            trigger:'blur'
        }
    ],
    productCount:[
        {
            type:'number',
            message:'您输入的内容不是数字哦！',
            trigger:'blur'
        },
        {
            required:true,
            message:'数量不能为空！',
            trigger:'blur'
        }
    ],
    price:[
        {
            type:'number',
            message:'您输入的价格不是数字哦！',
            trigger:'blur'
        },
        {
            required:true,
            message:'价格不能为空！',
            trigger:'blur'
        }
    ],
    brand:[
        {
            required:true,
            message:'品牌不能为空',
            trigger:'blur'
        }
    ],
    sizeCheckList:[
        {
            type:'array',
            required:true,
            message:'至少选择一项尺寸',
            trigger:'change'
        }
    ],
    seasonCheckList:[
        {
            type:'array',
            required:true,
            message:'至少选择一项季节',
            trigger:'change'
        }
    ],
    collarTypeCheckList:[
        {
            type:'array',
            required:true,
            message:'至少选择一项领型',
            trigger:'change'
        }
    ]
}
