interface rulesInterface {
    description:[
        {
            required:boolean,
            message:string,
            trigger:string
        }
    ],
    imageLink:[
        {
            required:boolean,
            message:string,
            trigger:string
        }
    ],
    productCount:[
        {
            required:boolean,
            message:string,
            trigger:string
        },
        {
            type:string,
            message:string,
            trigger:string
        }
    ],
    price:[
        {
            required:boolean,
            message:string,
            trigger:string
        },
        {
            type:string,
            message:string,
            trigger:string
        }
    ],
    brand:[
        {
            required:boolean,
            message:string,
            trigger:string
        }
    ],
    sizeCheckList: [
        {
            type:string,
            required:boolean,
            message:string,
            trigger:string
        }
    ],
    seasonCheckList: [
        {
            type:string,
            required:boolean,
            message:string,
            trigger:string
        }
    ],
    collarTypeCheckList: [
        {
            type:string,
            required:boolean,
            message:string,
            trigger:string
        }
    ],
}

let rules:rulesInterface={
    description:[
        {
            required:true,
            message:'图片描述不能为空!',
            trigger:'blur'
        }
    ],
    imageLink:[
        {
            required:true,
            message:'链接不能为空!',
            trigger:'blur'
        }
    ],
    productCount:[
        {
            required:true,
            message:'数量不能为空!',
            trigger:'blur'
        },
        {
            type:'number',
            message:'您的输入的不是数字哦!',
            trigger:'blur'
        }
    ],
    price:[
        {
            required:true,
            message:'价格不能为空!',
            trigger:'blur'
        },
        {
            type:'number',
            message:'价格必须是数字哦!',
            trigger:'blur'
        }
    ],
    brand:[
        {
            required:true,
            message:'品牌不能为空!',
            trigger:'blur'
        }
    ],
    sizeCheckList: [
        {
            type:'array',
            required:true,
            message:'至少选择一项哦！',
            trigger:'change'
        }
    ],
    seasonCheckList: [
        {
            type:'array',
            required:true,
            message:'至少选择一项哦！',
            trigger:'change'
        }
    ],
    collarTypeCheckList: [
        {
            type:'array',
            required:true,
            message:'至少选择一项哦！',
            trigger:'change'
        }
    ],
}
export default rules